### PR TITLE
:memo: Add types declaration file

### LINKED ISSUE #45: TypeScript support
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

### PR DESCRIPTION
**Pull request by geopic**
Resolves #45. I've typed the whole project but will leave it to you guys to iron out the small faults which undoubtedly will be there in a 1100+ line types file. Cheers :+1:

### CODE REVIEW

**Comment by clabe45** [comment]
Sorry for the late response. I just started learning typescript to work with this, but I found out that it might be better to convert the whole source code to typescript. That way, if the API changes, typescript can create another declaration file for us, and we won't risk them being out of sync. I can tell you put a lot of work into this, and I don't want that to go to waste. I could use that to port src/ to typescript. Again, I am new to typescript, what do you think of this idea?

**Comment by geopic** [comment]
It sounds fine mate, I'm happy for the types file to be of assistance to you porting this project to TS. :smile: If you need any help in transferring to TS then feel free to let me know.

**Comment by clabe45** [comment]
Alright haha. I'll make a new branch for typescript support. I think it would be better to merge this pull request into that branch, and we can use the declaration file for reference there. I don't have permission to change the pull request so could you change that? It should be configured to compile the typescript, so now I just need to start porting it. I will also create a new pull request from my typescript branch to master. If you want to take a look, you can leave comments there! Thank you so much.

**Comment by geopic** [comment]
Done. :+1:

**Pull request merged**
